
###
GET http://localhost:3000/metrics 

###
OPTIONS http://localhost:3000/api/v1/rpc/system.health 

###
POST http://localhost:3000/api/v1/rpc/test.pong


###
POST http://localhost:3000/api/v1/rpc/system.commands


###
POST http://localhost:3000/api/v1/rpc/test.echo
Content-Type: application/json

{
    "a":1,
    "b":"hello",
    "c":[1,2,3,4]
}
